[settings]
idiomatic_version_file_enable_tools = ["python"]
minimum_release_age = "14d"
experimental = true

[tools]
doppler = "latest"
glow = "latest"
jj = "latest"
node = "latest"
"npm:agent-browser" = "latest"
prek = "latest"
terraform = "latest"
"github:anchore/grype" = "latest"
"github:anchore/syft" = "latest"
"github:sxyazi/yazi" = "latest"
yazi = "latest"
terragrunt = "latest"
go = "latest"
ruff = "latest"
atuin = "latest"
"cargo:kanata" = "latest"
eza = "latest"
"github:astral-sh/uv" = "latest"
"github:astral-sh/ruff" = "latest"
lazygit = "latest"
lazydocker = "latest"
gum = "latest"
yq = "latest"
"github:muesli/duf" = "latest"
"github:bcicen/ctop" = "latest"
"github:aristocratos/btop" = "latest"
fd = "latest"
bat = "latest"
ripgrep = "latest"
fzf = "latest"
sops = "latest"
age = "latest"
bitwarden = "latest"
starship = "latest"
zoxide = "latest"
jq = "latest"
age-plugin-yubikey = "latest"
just = "latest"
"github:alexpasmantier/television" = "latest"
fnox = "latest"
"github:joshmedeski/sesh" = "latest"
"github:charmbracelet/mods" = "latest"
"github:lightonai/next-plaid" = "latest"
glab = "latest"
"github:ogulcancelik/herdr" = "latest"
gh = "latest"
"github:agavra/tuicr" = "latest"
