#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = [
#   "faster-whisper>=1.1.1",
#   "loguru>=0.7.3",
#   "pyperclip>=1.9.0",
#   "rich>=13.9.4",
#   "sounddevice>=0.5.1",
#   "soundfile>=0.13.1",
#   "typer>=0.15.2",
# ]
# ///

import sounddevice as sd
import soundfile as sf
from faster_whisper import WhisperModel
import time
from loguru import logger
from rich import print as rprint
from uuid import uuid4
import argparse
import pyperclip
import shutil


def list_input_devices():
    rprint("Available input devices:")
    for i, device in enumerate(sd.query_devices()):
        if device.get("max_input_channels", 0) > 0:  # type: ignore
            rprint(f"{i}: {device['name']}")  # type: ignore


def record_audio(duration, samplerate, channels, device) -> str:
    rprint(f"Recording for {duration} seconds...")
    filename = "/tmp/" + str(uuid4()) + ".wav"
    try:
        audio_data = sd.rec(
            int(duration * samplerate),
            samplerate=samplerate,
            channels=channels,
            dtype="int16",
            device=device,
        )
        sd.wait()
        sf.write(filename, audio_data, samplerate)
        logger.debug(f"Saved recording to '{filename}'")
    except Exception as e:
        logger.error(f"Error during recording: {e}")

    return filename




def transcribe(
    filename: str,
    model_name: str = "tiny",
):
    logger.debug(f"Loading model: {model_name}")
    model = WhisperModel(model_name)

    start_time = time.monotonic()
    segments, info = model.transcribe(filename)
    text = ""
    for segment in segments:
        print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))
        text += segment.text

    logger.debug(f"Transcription took: {(time.monotonic() - start_time)}s")

    return text


def main():
    parser = argparse.ArgumentParser(
        description="Simple audio recorder using sounddevice."
    )
    parser.add_argument(
        "-l",
        "--list-devices",
        action="store_true",
        help="List available input devices and exit",
    )
    parser.add_argument(
        "-d", "--device", type=int, help="Input device index (default: system default)"
    )
    parser.add_argument(
        "-t", "--time", type=int, default=5, help="Duration of recording in seconds"
    )
    parser.add_argument(
        "-m",
        "--model",
        type=str,
        default="tiny",
        help="Name of the faster whisper model to use",
    )
    parser.add_argument(
        "-r",
        "--rate",
        type=int,
        default=44100,
        help="Sampling rate (default: 44100 Hz)",
    )
    parser.add_argument(
        "-c",
        "--channels",
        type=int,
        default=1,
        help="Number of input channels (1=mono, 2=stereo)",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=str,
        default=None,
        help="Optional location to store the recorded audio.",
    )
    parser.add_argument(
        "--convert",
        action="store_true",
        help="Optional way to convert a huggingface ASR model to be used for faster-whisper"
    )

    args = parser.parse_args()

    if args.list_devices:
        list_input_devices()
    elif args.convert:
        convert(args.model)
    else:
        recording_file = record_audio(
            duration=args.time,
            samplerate=args.rate,
            channels=args.channels,
            device=args.device,
        )
        text = transcribe(recording_file, args.model)
        pyperclip.copy(text)
        logger.debug("Copied to clipboard")
        if args.output:
            shutil.copy(recording_file, args.output)


if __name__ == "__main__":
    main()
