-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
---- make zsh files recognized as sh for bash-ls & treesitter

-- vim.filetype.add {
-- 	extension = {
-- 		zsh = "sh",
-- 		sh = "sh", -- force sh-files with zsh-shebang to still get sh as filetype
-- 	},
-- 	filename = {
-- 		[".zshrc"] = "sh",
-- 		[".zshenv"] = "sh",
-- 	},
-- }
